### ISSUE TITLE
Request: Ability to set space between rows and columns and other announced improvements.

### ISSUE THREAD

**Issue by davidvb** [marianomike/sketch-organizesymbols#2]
Hello, your announced update never materialised unfortunately. Any chance of adding those features, or do you recommend an alternative plugin?

**Comment by marianomike** [comment]
Hey David, sorry I totally missed this request. And yes, I haven't done much work on this unfortunately. But I'd highly recommend this alternative plugin: https://github.com/sonburn/symbol-organizer
